# Generated by Django 6.0.6 on 2026-06-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('staus', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
