# Generated by Django 6.0.6 on 2026-07-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='salary',
            field=models.IntegerField(default=50000),
            preserve_default=False,
        ),
    ]
