# Generated by Django 6.0.6 on 2026-07-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_employees_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='Allowance',
            field=models.IntegerField(default=30000),
        ),
    ]
