# Generated by Django 6.0.6 on 2026-07-02 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_employees_allowance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='staus',
            new_name='status',
        ),
    ]
